-- MySQL Script generated by MySQL Workbench
-- Tue Jun  1 21:34:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tasksDatabase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tasksDatabase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tasksDatabase` DEFAULT CHARACTER SET utf8 ;
USE `tasksDatabase` ;

-- -----------------------------------------------------
-- Table `tasksDatabase`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasksDatabase`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasksDatabase`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasksDatabase`.`tasks` (
  `idtasks` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `state` VARCHAR(10) NOT NULL DEFAULT 'Pendiente',
  `idusers` INT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `delete_at` datetime NOT NULL,
  PRIMARY KEY (`idtasks`),
  INDEX `idusers_idx` (`idusers` ASC),
  CONSTRAINT `idusers`
    FOREIGN KEY (`idusers`)
    REFERENCES `tasksDatabase`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
